car (
   color "DarkSlateGray"
   pose [-36.98 -23.18 3.69]
   bitmap "cars/car5.png"
)

car (
   color "DeepSkyBlue1"
   pose [-37.16 -10.94 2.01]
   bitmap "cars/car3.png"
)

car (
   color "DarkCyan"
   pose [-36.82 -5.94 -6.45]
   bitmap "cars/car2.png"
)

car (
   color "DarkOrchid1"
   pose [-37.1 5.87 -6.12]
   bitmap "cars/car4.png"
)

car (
   color "DarkGreen"
   pose [-37.17 11.09 -6.76]
   bitmap "cars/car1.png"
)

car (
   color "DarkGreen"
   pose [-37.17 23.15 0.31]
   bitmap "cars/car5.png"
)

car (
   color "aquamarine4"
   pose [-34.03 -23.08 -2.56]
   bitmap "cars/car4.png"
)

car (
   color "DarkOrchid1"
   pose [-34.13 -11.08 -4.5]
   bitmap "cars/car1.png"
)

car (
   color "red"
   pose [-33.83 -5.82 7.31]
   bitmap "cars/car1.png"
)

car (
   color "maroon1"
   pose [-34.1 6.05 7.66]
   bitmap "cars/car5.png"
)

car (
   color "DarkRed"
   pose [-33.82 11.08 -2.82]
   bitmap "cars/car4.png"
)

car (
   color "DarkMagenta"
   pose [-33.85 23.03 -5.21]
   bitmap "cars/car1.png"
)

car (
   color "SteelBlue1"
   pose [-30.82 -22.96 -0.3]
   bitmap "cars/car3.png"
)

car (
   color "SteelBlue1"
   pose [-30.86 -10.99 4.0]
   bitmap "cars/car2.png"
)

car (
   color "DarkRed"
   pose [-31.05 -5.97 -7.24]
   bitmap "cars/car4.png"
)

car (
   color "blue"
   pose [-31.16 5.92 7.9]
   bitmap "cars/car5.png"
)

car (
   color "DarkOrchid1"
   pose [-30.84 11.13 -3.61]
   bitmap "cars/car5.png"
)

car (
   color "DarkMagenta"
   pose [-31.07 22.84 -6.52]
   bitmap "cars/car4.png"
)

car (
   color "pink1"
   pose [-28.07 -22.93 7.59]
   bitmap "cars/car4.png"
)

car (
   color "navy"
   pose [-28.02 -11.06 6.35]
   bitmap "cars/car2.png"
)

car (
   color "DeepSkyBlue1"
   pose [-27.88 -6.17 -7.22]
   bitmap "cars/car1.png"
)

car (
   color "blue"
   pose [-28.1 6.12 -2.02]
   bitmap "cars/car5.png"
)

car (
   color "DarkMagenta"
   pose [-27.86 10.95 0.85]
   bitmap "cars/car3.png"
)

car (
   color "maroon4"
   pose [-28.17 22.87 3.18]
   bitmap "cars/car4.png"
)

car (
   color "red"
   pose [-25.05 -22.97 1.78]
   bitmap "cars/car5.png"
)

car (
   color "DarkCyan"
   pose [-25.12 -11.01 -0.33]
   bitmap "cars/car2.png"
)

car (
   color "DeepSkyBlue1"
   pose [-25.15 -6.16 -6.74]
   bitmap "cars/car5.png"
)

car (
   color "green"
   pose [-24.82 6.02 -5.72]
   bitmap "cars/car5.png"
)

car (
   color "black"
   pose [-25.1 10.83 1.42]
   bitmap "cars/car3.png"
)

car (
   color "blue"
   pose [-24.95 22.95 -3.73]
   bitmap "cars/car4.png"
)

car (
   color "SteelBlue1"
   pose [-22.19 -23.11 -2.85]
   bitmap "cars/car2.png"
)

car (
   color "blue"
   pose [-22.14 -11.01 1.58]
   bitmap "cars/car5.png"
)

car (
   color "cyan1"
   pose [-21.85 -6.11 3.4]
   bitmap "cars/car4.png"
)

car (
   color "aquamarine4"
   pose [-22.01 5.81 1.58]
   bitmap "cars/car2.png"
)

car (
   color "DarkOrange"
   pose [-22.11 10.92 5.01]
   bitmap "cars/car1.png"
)

car (
   color "maroon1"
   pose [-22.03 22.95 -5.86]
   bitmap "cars/car2.png"
)

car (
   color "maroon1"
   pose [-19.2 -22.88 7.88]
   bitmap "cars/car2.png"
)

car (
   color "black"
   pose [-19.13 -10.98 -3.99]
   bitmap "cars/car1.png"
)

car (
   color "VioletRed1"
   pose [-18.92 -6.02 -3.65]
   bitmap "cars/car4.png"
)

car (
   color "green"
   pose [-19.08 6.0 -6.22]
   bitmap "cars/car4.png"
)

car (
   color "DarkOrange"
   pose [-19.09 10.82 -5.5]
   bitmap "cars/car3.png"
)

car (
   color "maroon1"
   pose [-19.01 23.02 4.17]
   bitmap "cars/car3.png"
)

car (
   color "DarkMagenta"
   pose [-16.18 -23.04 -0.46]
   bitmap "cars/car2.png"
)

car (
   color "cyan1"
   pose [-15.9 -10.91 2.95]
   bitmap "cars/car5.png"
)

car (
   color "DarkCyan"
   pose [-16.11 -6.09 -3.56]
   bitmap "cars/car1.png"
)

car (
   color "DarkOrange"
   pose [-15.99 6.14 -5.88]
   bitmap "cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [-16.11 11.07 7.44]
   bitmap "cars/car4.png"
)

car (
   color "VioletRed1"
   pose [-15.88 22.88 4.6]
   bitmap "cars/car4.png"
)

car (
   color "DarkSlateGray"
   pose [-12.91 -22.85 4.42]
   bitmap "cars/car4.png"
)

car (
   color "DarkRed"
   pose [-13.07 -11.16 -2.49]
   bitmap "cars/car4.png"
)

car (
   color "maroon4"
   pose [-12.95 -5.89 4.56]
   bitmap "cars/car4.png"
)

car (
   color "VioletRed1"
   pose [-13.11 5.95 3.27]
   bitmap "cars/car2.png"
)

car (
   color "maroon4"
   pose [-12.91 11.11 -4.89]
   bitmap "cars/car4.png"
)

car (
   color "aquamarine4"
   pose [-13.0 23.09 -3.53]
   bitmap "cars/car3.png"
)

car (
   color "black"
   pose [-9.87 -23.15 4.12]
   bitmap "cars/car3.png"
)

car (
   color "SeaGreen"
   pose [-10.12 -11.19 3.9]
   bitmap "cars/car4.png"
)

car (
   color "DeepSkyBlue1"
   pose [-10.19 -6.17 5.18]
   bitmap "cars/car3.png"
)

car (
   color "SeaGreen"
   pose [-10.05 6.07 -5.59]
   bitmap "cars/car2.png"
)

car (
   color "blue"
   pose [-10.17 11.15 -5.13]
   bitmap "cars/car1.png"
)

car (
   color "SeaGreen"
   pose [-10.19 23.12 3.17]
   bitmap "cars/car1.png"
)

car (
   color "cyan1"
   pose [-6.97 -22.99 -1.79]
   bitmap "cars/car2.png"
)

car (
   color "chocolate1"
   pose [-7.16 -10.98 3.5]
   bitmap "cars/car2.png"
)

car (
   color "SeaGreen"
   pose [-6.81 -6.01 -7.87]
   bitmap "cars/car3.png"
)

car (
   color "DarkBlue"
   pose [-6.84 5.9 6.45]
   bitmap "cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [-7.14 10.84 -3.91]
   bitmap "cars/car5.png"
)

car (
   color "DarkBlue"
   pose [-7.01 23.08 4.48]
   bitmap "cars/car4.png"
)

car (
   color "magenta1"
   pose [-4.03 -22.92 -3.55]
   bitmap "cars/car3.png"
)

car (
   color "aquamarine4"
   pose [-4.02 -10.86 -3.68]
   bitmap "cars/car5.png"
)

car (
   color "DarkOrange"
   pose [-4.06 -6.1 -0.66]
   bitmap "cars/car3.png"
)

car (
   color "maroon1"
   pose [-4.14 5.86 3.54]
   bitmap "cars/car2.png"
)

car (
   color "aquamarine4"
   pose [-3.9 10.88 7.89]
   bitmap "cars/car2.png"
)

car (
   color "black"
   pose [-3.89 22.82 7.95]
   bitmap "cars/car1.png"
)

car (
   color "DarkMagenta"
   pose [-0.95 -22.8 1.5]
   bitmap "cars/car3.png"
)

car (
   color "DarkCyan"
   pose [-1.08 -11.06 -3.77]
   bitmap "cars/car1.png"
)

car (
   color "maroon4"
   pose [-0.94 -5.95 -0.93]
   bitmap "cars/car2.png"
)

car (
   color "VioletRed1"
   pose [-1.11 5.94 -4.55]
   bitmap "cars/car5.png"
)

car (
   color "maroon4"
   pose [-0.83 11.18 -7.65]
   bitmap "cars/car4.png"
)

car (
   color "black"
   pose [-0.84 23.01 -3.01]
   bitmap "cars/car5.png"
)

car (
   color "DeepSkyBlue1"
   pose [1.89 -23.12 0.25]
   bitmap "cars/car4.png"
)

car (
   color "magenta1"
   pose [1.9 -11.05 0.83]
   bitmap "cars/car1.png"
)

car (
   color "aquamarine4"
   pose [2.09 -5.93 -5.69]
   bitmap "cars/car4.png"
)

car (
   color "DarkRed"
   pose [1.98 6.03 7.36]
   bitmap "cars/car5.png"
)

car (
   color "DarkRed"
   pose [1.85 11.04 7.18]
   bitmap "cars/car1.png"
)

car (
   color "VioletRed1"
   pose [1.89 22.85 -2.6]
   bitmap "cars/car3.png"
)

car (
   color "VioletRed1"
   pose [5.15 -23.07 -7.65]
   bitmap "cars/car3.png"
)

car (
   color "black"
   pose [5.05 -10.84 -7.03]
   bitmap "cars/car4.png"
)

car (
   color "DarkSlateGray"
   pose [5.04 -6.18 0.98]
   bitmap "cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [5.11 6.14 -3.62]
   bitmap "cars/car2.png"
)

car (
   color "black"
   pose [4.92 11.17 4.37]
   bitmap "cars/car2.png"
)

car (
   color "black"
   pose [5.08 22.84 -3.9]
   bitmap "cars/car3.png"
)

car (
   color "pink1"
   pose [8.14 -23.14 2.52]
   bitmap "cars/car5.png"
)

car (
   color "aquamarine4"
   pose [8.16 -11.06 2.61]
   bitmap "cars/car5.png"
)

car (
   color "DarkRed"
   pose [7.91 -5.93 2.48]
   bitmap "cars/car3.png"
)

car (
   color "maroon4"
   pose [7.85 6.06 -1.72]
   bitmap "cars/car1.png"
)

car (
   color "DarkRed"
   pose [8.04 11.2 -6.33]
   bitmap "cars/car5.png"
)

car (
   color "green"
   pose [8.1 22.93 2.2]
   bitmap "cars/car5.png"
)

car (
   color "VioletRed1"
   pose [11.17 -22.95 1.51]
   bitmap "cars/car4.png"
)

car (
   color "maroon1"
   pose [10.9 -10.88 6.76]
   bitmap "cars/car3.png"
)

car (
   color "black"
   pose [10.89 -6.06 -5.52]
   bitmap "cars/car2.png"
)

car (
   color "green"
   pose [10.89 5.82 -4.16]
   bitmap "cars/car4.png"
)

car (
   color "chocolate1"
   pose [11.08 11.17 5.41]
   bitmap "cars/car5.png"
)

car (
   color "SeaGreen"
   pose [10.97 23.15 -0.2]
   bitmap "cars/car3.png"
)

car (
   color "DarkGreen"
   pose [14.0 -23.18 -4.35]
   bitmap "cars/car1.png"
)

car (
   color "DarkRed"
   pose [13.96 -11.04 3.73]
   bitmap "cars/car4.png"
)

car (
   color "cyan1"
   pose [13.86 -5.87 4.78]
   bitmap "cars/car5.png"
)

car (
   color "pink1"
   pose [14.1 5.87 -0.06]
   bitmap "cars/car3.png"
)

car (
   color "maroon4"
   pose [13.84 10.8 3.26]
   bitmap "cars/car2.png"
)

car (
   color "DeepSkyBlue1"
   pose [14.12 23.15 -5.34]
   bitmap "cars/car4.png"
)

car (
   color "chocolate1"
   pose [16.86 -22.95 2.38]
   bitmap "cars/car1.png"
)

car (
   color "turquoise1"
   pose [17.04 -10.8 -0.09]
   bitmap "cars/car5.png"
)

car (
   color "black"
   pose [16.86 -5.86 0.21]
   bitmap "cars/car2.png"
)

car (
   color "turquoise1"
   pose [17.05 6.13 -4.95]
   bitmap "cars/car1.png"
)

car (
   color "SeaGreen"
   pose [17.12 10.84 -5.17]
   bitmap "cars/car1.png"
)

car (
   color "aquamarine4"
   pose [17.19 22.93 3.77]
   bitmap "cars/car2.png"
)

car (
   color "DarkOrchid1"
   pose [20.07 -23.05 3.46]
   bitmap "cars/car2.png"
)

car (
   color "turquoise1"
   pose [19.97 -11.09 -3.33]
   bitmap "cars/car5.png"
)

car (
   color "green"
   pose [19.91 -5.87 5.78]
   bitmap "cars/car1.png"
)

car (
   color "black"
   pose [20.09 6.15 -2.64]
   bitmap "cars/car4.png"
)

car (
   color "navy"
   pose [20.08 10.84 -6.48]
   bitmap "cars/car1.png"
)

car (
   color "DarkOrange"
   pose [20.02 22.86 -5.61]
   bitmap "cars/car4.png"
)

car (
   color "magenta1"
   pose [23.13 -22.87 5.64]
   bitmap "cars/car1.png"
)

car (
   color "DarkMagenta"
   pose [22.84 -11.14 6.71]
   bitmap "cars/car4.png"
)

car (
   color "cyan1"
   pose [23.18 -5.82 6.05]
   bitmap "cars/car5.png"
)

car (
   color "VioletRed1"
   pose [23.04 5.95 4.47]
   bitmap "cars/car5.png"
)

car (
   color "chocolate1"
   pose [23.1 11.1 5.8]
   bitmap "cars/car2.png"
)

car (
   color "SteelBlue1"
   pose [23.18 22.99 -3.98]
   bitmap "cars/car2.png"
)

car (
   color "DarkCyan"
   pose [26.0 -22.89 -2.04]
   bitmap "cars/car5.png"
)

car (
   color "chocolate1"
   pose [26.13 -11.03 -0.5]
   bitmap "cars/car4.png"
)

car (
   color "DarkOrange"
   pose [25.84 -5.97 -5.88]
   bitmap "cars/car4.png"
)

car (
   color "VioletRed1"
   pose [25.83 6.09 -4.18]
   bitmap "cars/car5.png"
)

car (
   color "VioletRed1"
   pose [26.0 11.19 0.1]
   bitmap "cars/car2.png"
)

car (
   color "blue"
   pose [26.2 22.9 4.75]
   bitmap "cars/car2.png"
)

car (
   color "maroon4"
   pose [29.02 -23.12 0.73]
   bitmap "cars/car5.png"
)

car (
   color "DarkGreen"
   pose [29.06 -11.02 -6.58]
   bitmap "cars/car4.png"
)

car (
   color "cyan1"
   pose [28.88 -5.82 2.34]
   bitmap "cars/car4.png"
)

car (
   color "DarkCyan"
   pose [29.03 6.17 4.84]
   bitmap "cars/car3.png"
)

car (
   color "maroon4"
   pose [29.07 11.04 -1.52]
   bitmap "cars/car3.png"
)

car (
   color "blue"
   pose [29.01 23.18 -7.48]
   bitmap "cars/car1.png"
)

car (
   color "turquoise1"
   pose [41.07 -14.02 -85.63]
   bitmap "cars/car3.png"
)

car (
   color "DarkSlateGray"
   pose [41.1 -11.16 -87.82]
   bitmap "cars/car1.png"
)

car (
   color "aquamarine4"
   pose [41.13 -7.84 -88.65]
   bitmap "cars/car2.png"
)

car (
   color "magenta1"
   pose [41.02 -5.15 -93.55]
   bitmap "cars/car2.png"
)

car (
   color "DarkSlateGray"
   pose [40.94 -2.0 -85.95]
   bitmap "cars/car1.png"
)

car (
   color "chocolate1"
   pose [41.12 0.99 -85.91]
   bitmap "cars/car2.png"
)

car (
   color "navy"
   pose [41.01 4.12 -93.99]
   bitmap "cars/car3.png"
)

car (
   color "navy"
   pose [41.12 6.85 -87.53]
   bitmap "cars/car4.png"
)

car (
   color "maroon1"
   pose [40.9 9.84 -84.04]
   bitmap "cars/car2.png"
)

car (
   color "pink1"
   pose [41.1 13.09 -82.82]
   bitmap "cars/car5.png"
)

car (
   color "DarkSlateGray"
   pose [40.87 15.92 -84.74]
   bitmap "cars/car4.png"
)

car (
   color "maroon4"
   pose [40.92 19.04 -93.87]
   bitmap "cars/car3.png"
)

car (
   color "DarkRed"
   pose [40.83 22.04 -93.48]
   bitmap "cars/car2.png"
)

